spring:
  application:
    name: rentify

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  file:
    path: logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    web: error
    root: info
    sql: error

