server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:59144/railway
    username: root
    password: QdcvoKhoFAFzmeOTXtOAbwsZhEXiwwgf

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: hushenjuyel@gmail.com
    password: <PASSWORD>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



#Secret Key
Secret:
  key: <SecretKey>

#AWS properties
aws:
  accessKey: <AWS_ACCESS_KEY>
  secretKey: <AWS_SECRET_KEY>
  region: ap-south-1

  s3:
    bucket:
      name: rentify-in-bucket
      url: https://rentify-in-bucket.s3.ap-south-1.amazonaws.com


